# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: 'machine_common_sense/|scripts/|tests/|integration_tests/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
-   repo: local
    hooks:
    -   id: sphinx
        name: sphinx
        entry: ./scripts/generate_sphinx_docs.sh
        language: script
        verbose: true
