name: Test Publish to PyPI

on:
  push:
    branches:
      MCS-821-pypiAction

jobs:
  build-n-pub:
    strategy:
      matrix:
        # we are building a pure python wheel so it should work on any platform
        os: [ubuntu-latest]
        python-versions: [3.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest
      - name: Flake8
        run: flake8
      - name: Autopep8
        run: autopep8 --in-place --aggressive --recursive machine_common_sense
      - name: create wheel file
        run: python setup.py bdist_wheel sdist clean --all       
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/